name: blog_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  supabase_flutter: ^2.6.0
  logger: ^2.4.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  flutter_easyloading: ^3.0.5
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  json_serializable: ^6.8.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/image/
